const nock = require('/workspace/node_modules/nock').default;
const { appendFileSync } = require('node:fs');
nock.disableNetConnect();
nock.enableNetConnect(/^(127\.0\.0\.1|localhost|\[::1\])/);
nock('https://data.flashdata.dev', { reqheaders: { 'x-api-key': 'test-key-not-a-secret' } })
	.persist()
	.post('/v1/queries/realtime')
	.reply(async function (request) {
		const body = await request.json();
		appendFileSync('/fixtures/requests.jsonl', JSON.stringify(body) + '\n');
		if (body.query === 'simulate-payment-error')
			return [402, { error: true, message: 'Insufficient credits' }];
		const result = {
			google_search: {
				organic: [
					{
						title: body.query,
						link: 'https://example.com/research',
						snippet: 'Search fixture',
						position: 1,
					},
				],
			},
			youtube_search: {
				results: [{ videoId: 'dQw4w9WgXcQ', title: body.query, channel: 'Example' }],
			},
			youtube_metadata: { videoId: body.video_id, title: 'Example video', channel: 'Example' },
			youtube_transcript: {
				videoId: body.video_id,
				languageCode: body.params?.language || 'en',
				isAutoGenerated: body.params?.auto ?? true,
				segments: [{ start: 0, end: 3, text: 'Example transcript.' }],
			},
		}[body.source];
		return result
			? [
					200,
					{
						source: body.source,
						status: 'done',
						results: [result],
						usage: { credits: 0.01 },
						created_at: '2026-10-08T00:00:00Z',
					},
				]
			: [400, { error: true, message: 'Unknown source' }];
	});
